tyler-mcwilliam/Lavender

- app/controllers/groups_controller.rb
- app/controllers/orders_controller.rb
- app/controllers/polls_controller.rb
- app/controllers/positions_controller.rb
- app/controllers/user_groups_controller.rb
- app/controllers/votes_controller.rb
- test/controllers/groups_controller_test.rb
- test/controllers/orders_controller_test.rb
- test/controllers/polls_controller_test.rb
- test/controllers/positions_controller_test.rb
- test/controllers/user_groups_controller_test.rb
- test/controllers/votes_controller_test.rb
created controller skeleton. very basic
> controller frames created

- Gemfile
- app/controllers/sessions_controller.rb
- app/models/user.rb
- config/initializers/omniauth.rb
- db/migrate/20190603095417_devise_create_users.rb
Need to push code to master so I can pull down all the remaining changes so I can pull from new master
> Need to push code to master so I can pull down all the remaining changes

- app/controllers/groups_controller.rb
- app/controllers/orders_controller.rb
- app/controllers/polls_controller.rb
- app/controllers/positions_controller.rb
- app/controllers/user_groups_controller.rb
- app/controllers/votes_controller.rb
tripple check this one. made a lot of starter controller methods, but not finalized.
> Controller methods

- app/controllers/groups_controller.rb
- app/views/groups/show.html.erb
- app/views/shared/_navbar.html.erb
> Linking buttons

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_forms.scss
- app/assets/stylesheets/components/_googlebutton.scss
- app/assets/stylesheets/components/_index.scss
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
Completed styling of signup form and color and style. It took longer than expected. I commented out the css for tylers button to expand.  If someone wants to take a crack at it go for it.
> Signup form

- app/controllers/polls_controller.rb
- app/views/polls/show.html.erb
> More routes

- app/views/users/dashboard.html.erb
- config/routes.rb
> updated the join group button in dashboard

- app/assets/stylesheets/components/_forms.scss
- app/views/groups/index.html.erb
- app/views/users/dashboard.html.erb
> added group index and modal form

- app/views/shared/_navbar.html.erb
- app/views/users/dashboard.html.erb
Error loading navbar because current_user.photo = nil
Added control flow to use on of tyler's monsters as default when current_user.photo = nil
> navbar error

- app/views/shared/_navbar.html.erb
- app/views/users/dashboard.html.erb
Reverts tyler-mcwilliam/Lavender#39
I dont think this was an error
> Revert "navbar error"

- app/controllers/votes_controller.rb
- app/views/groups/show.html.erb
> displays approval status

- app/views/shared/_footer.html.erb
> made the about button take you to the home page

- app/controllers/groups_controller.rb
- app/controllers/orders_controller.rb
- app/controllers/votes_controller.rb
- app/models/order.rb
- app/models/position.rb
- db/migrate/20190606091632_add_filled_to_orders.rb
- db/schema.rb
this has updates to schema and models
> creates orders!

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/pages/_dashboard.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/users/dashboard.html.erb
- db/schema.rb
> Center footer

- app/assets/stylesheets/pages/_dashboard.scss
- app/assets/stylesheets/pages/_side_bars.scss
- app/controllers/groups_controller.rb
- app/views/groups/_show.html.erb
- app/views/groups/show.html.erb
- app/views/shared/_modal_group_deposit.html.erb
- app/views/shared/_modal_group_withdraw.html.erb
- app/views/shared/_modal_user_deposit.html.erb
- app/views/shared/_modal_user_withdraw.html.erb
- app/views/users/dashboard.html.erb
- changed poll IDs so that user deposit/withdrawals can be differentiated from groups
- fixed poll form
- resized group-view-container so that it doesn't cover buttons
> Fix trade button

- app/controllers/groups_controller.rb
- app/models/user.rb
- app/views/devise/registrations/new.html.erb
- app/views/groups/index.html.erb
- db/migrate/20190604030108_add_columns_to_users.rb
- db/schema.rb
> Adjusted birthday and added gender

- app/views/groups/create.js.erb
- app/views/users/dashboard.html.erb
utilized event delegation on group tabs to enable event listening om dynamic views
> fixed event listening

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/pages/_dashboard.scss
- app/assets/stylesheets/pages/_group_index.scss
- app/assets/stylesheets/pages/_group_show.scss
- app/assets/stylesheets/pages/_side_bars.scss
- app/controllers/groups_controller.rb
- app/controllers/user_groups_controller.rb
- app/views/groups/_index.html.erb
- app/views/groups/_show.html.erb
- app/views/groups/index.js.erb
- app/views/groups/show.js.erb
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- app/views/partials/_groups_container.html.erb
- app/views/partials/_orders_container.html.erb
- app/views/partials/_polls_container.html.erb
- app/views/shared/_chat.html.erb
- app/views/shared/_modal_join_group.html.erb
- app/views/user_groups/create.js.erb
- app/views/users/dashboard.html.erb
- app/views/votes/create.js.erb
> Group index ajax

- app/views/partials/_groups_container.html.erb
> percentages displayed in descending order

- app/assets/stylesheets/components/_polls.scss
- app/assets/stylesheets/pages/_dashboard.scss
- app/assets/stylesheets/pages/_group_show.scss
- app/views/groups/_show.html.erb
- app/views/partials/_orders_container.html.erb
- app/views/partials/_polls_container.html.erb
merge this so i can show my friends lol
> should be better for macbooks now
